# active spring boot profile
spring:
   profiles:
      active: dev

---
# common - spring configuration
spring:

   # devtools - live reload
   devtools:
      livereload:
         enabled: true

   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp

---

# dev profile - spring boot configuration

spring:
   config:
      activate:
         on-profile: dev
      
   # datasource
   datasource:
      username: root
      password: 1111
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://localhost:3306/booksystem?characterEncoding=utf8

---

#mybatis
mybatis:
  config-location: classpath:mybatis/configuration.xml
  
---
spring: 
  servlet:
    multipart:
      max-file-size: 10MB 
      max-request-size: 10MB
      location: C:\Users\PC\workspace\01. 이전 프로젝트\01. 도서관리시스템\BookSys\bookfe\public\img
